<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <ApplicationIcon>Resources\icon.ico</ApplicationIcon>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\CorrectionsList.json" />
    <None Remove="Resources\defaultHeroIcon.png" />
    <None Remove="Resources\DownloadSources.json" />
    <None Remove="Resources\Help\用户手册.pdf" />
    <None Remove="Resources\Languages\zh-CN.json" />
    <None Remove="Resources\Languages\en-US.json" />
    <None Remove="Resources\Models\PP-OCRv5_mobile_det_infer\inference.json" />
    <None Remove="Resources\Models\PP-OCRv5_mobile_det_infer\inference.pdiparams" />
    <None Remove="Resources\Models\PP-OCRv5_mobile_det_infer\inference.yml" />
    <None Remove="Resources\Models\PP-OCRv5_mobile_rec_infer\inference.json" />
    <None Remove="Resources\Models\PP-OCRv5_mobile_rec_infer\inference.pdiparams" />
    <None Remove="Resources\Models\PP-OCRv5_mobile_rec_infer\inference.yml" />
    <None Remove="Resources\Models\ppocr_keys_v5.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\CorrectionsList.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\defaultHeroIcon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\DownloadSources.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Help\用户手册.pdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\icon.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Languages\zh-CN.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Languages\en-US.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Models\PP-OCRv5_mobile_det_infer\inference.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Models\PP-OCRv5_mobile_det_infer\inference.pdiparams">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Models\PP-OCRv5_mobile_det_infer\inference.yml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Models\PP-OCRv5_mobile_rec_infer\inference.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Models\PP-OCRv5_mobile_rec_infer\inference.pdiparams">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Models\PP-OCRv5_mobile_rec_infer\inference.yml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Models\ppocr_keys_v5.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="OpenCvSharp4" Version="4.11.0.20250507" />
    <PackageReference Include="OpenCvSharp4.Extensions" Version="4.11.0.20250507" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.11.0.20250507" />
    <PackageReference Include="Sdcb.PaddleInference" Version="3.0.1" />
    <PackageReference Include="Sdcb.PaddleInference.runtime.win64.cu129_cudnn910_sm89" Version="3.1.0.54" />
    <PackageReference Include="Sdcb.PaddleOCR" Version="3.0.1" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.9" />
    <PackageReference Include="System.Management" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Forms\ToolForm\EquipmentDataEditorForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\HeroDatas\**\*" />
    <Content Include="Resources\HeroDatas\**\*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>